FriendsFirst.Web/Models/Projections/Projection.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FriendsFirst.Web.Models.Projections
{
    public class Projection
    {
        public ProjectionAlteration[] Alterations { get; set; }
        public Projection()
        {
            this.Alterations = new ProjectionAlteration[] { };
        }

        public FriendsFirst.Contracts.StandardSavingsContract Contract { get; set; }
        public IEnumerable<FriendsFirst.Projections.ProjectedContract<FriendsFirst.Contracts.StandardSavingsContract>> Projections { get; set; }

    }
}

FriendsFirst.Web/Models/Projections/ProjectionAlteration.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FriendsFirst.Web.Models.Projections
{
    /// <summary>
    /// Selection of options that can be applied to a projection
    /// </summary>
    public class ProjectionAlteration
    {
        /// <summary>
        /// Property that is to be altered
        /// </summary>
        public System.Reflection.PropertyInfo Property { get; set; }

        /// <summary>
        /// New value to set the property to
        /// </summary>
        public object Value { get; set; }
    }

    
}

FriendsFirst.Web/Models/TestContracts.cs
using FriendsFirst.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FriendsFirst.Web.Models
{
    public static class TestContracts
    {
        public static FriendsFirst.Contracts.StandardSavingsContract SavingsContract
        {
            get {
                return new Contracts.StandardSavingsContract()
                {
                    ContractNumber = "50416217",
                    CommencmentDate = new DateTime(2016, 10, 14),
                    Matures = new DateTime(2016, 10, 14).AddYears(25),

                    Premium = new Premiums.RegulerPaying(Premiums.PremiumFrequency.Monthly)
                    {
                        Amount = 1000.00,
                        IndexationRate = 0.15,
                        Status = Premiums.PremiumStatuses.InForce
                    },
                    Coverages = new Entities.Person[]
                    {
                        new Person(){
                            Name = "Joe Blogg",
                            Gender = Genders.Male,
                            DOB = new DateTime(1968, 07, 27)
                        },
                        new Person(){
                            Name = "Jane Blogg",
                            Gender = Genders.Female,
                            DOB = new DateTime(1969, 08, 28)
                        }
                    },
                    Product = new Products.StandardPensionProduct()
                    {
                        Description = "Conductor Savings Plan",
                        Code = "ZSR",

                        Charge = 3.5,
                        ChargeIncreasesRate = 0.015,
                        ChargePercent = 1.0,
                    },

                    Funds = new Funds.InvestedFunds()
                    {
                        Items = new Funds.Fund[]
                        {
                            new Funds.UnitLinkedFund()
                            {
                                Code = "606",
                                GrowthRate = 0.05,
                                Name = "With Profit",
                                ManagmentCharge = 0.0075,
                                InitalUnitDiscountFactor = 1,
                                InvestmentPercent = 1,
                                Units = new Funds.Unit(
                                    0,
                                    152.55336,
                                    1.701,
                                    1.701,
                                    0)
                            }
                        }
                    }
                };
            }

        }
        
    }
}

FriendsFirst.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FriendsFirst.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

FriendsFirst.Web/Controllers/ProjectionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FriendsFirst.Web.Controllers
{
    public class ProjectionsController : Controller
    {
        // GET: Projections
        public ActionResult Index()
        {
            var model = new FriendsFirst.Web.Models.Projections.Projection()
            {
                Contract = FriendsFirst.Web.Models.TestContracts.SavingsContract,
                Projections = new List<FriendsFirst.Projections.ProjectedContract<FriendsFirst.Contracts.StandardSavingsContract>>()
            };
            return View(model);
        }

        public ActionResult Project(FormCollection form)
        {
            var Alterations = new FriendsFirst.Web.Models.Projections.ProjectionAlteration[] { };
            //Get the Contract
            var contract = FriendsFirst.Web.Models.TestContracts.SavingsContract;

            //Apply any alterations that have been provided
            

            //Create a projection
            var projector = new FriendsFirst.Projections.Projection<FriendsFirst.Contracts.StandardSavingsContract>(
                contract);

            //Project to maturity date
            var projection = projector[contract.Matures];

            //Create a new view model from the projection
            var model = new Web.Models.Projections.Projection()
            {
                Contract = contract,
                Projections = projector.Projections
            };

            //Return the projection.
            return View("index", model);
        }

        List<object> Alterations(ref FriendsFirst.Contracts.StandardSavingsContract contract, FormCollection form)
        {

            //Check all of the form values and if diffrent from the contract 
            //then update the contract and record the old and new values.


            return new List<object>();
        }
    }
}

FriendsFirst.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

FriendsFirst.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

FriendsFirst.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

FriendsFirst.Web/Views/Projections/Index.cshtml
@model FriendsFirst.Web.Models.Projections.Projection

@using (Html.BeginForm("Project", "Projections", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col-md-6">
            @Html.Partial("_Contract", Model.Contract)
        </div>

        <div class="col-md-6">
            <div class="row">
                @Html.Partial("_ContractSummary", Model.Contract)

                <div class="form-group col-md-offset-11">
                    <input type="submit" value="Project" class="btn btn-default" />
                </div>

            </div>
            @Html.Partial("_ProjectionsChart", Model.Projections)
        </div>

    </div>
 
}

<script type="text/javascript">
//$(function () {
//    //Loop through all Labels with class 'editable'.
//    $(".editable").each(function () {
//        //Reference the Label.
//        var label = $(this);

//        //Highlight the label 
//        label.css("font-weight", "Bold");

//        //Add a TextBox next to the Label.
//        label.after("<input type = 'text' style = 'display:none' />");

//        //Reference the TextBox.
//        var textbox = $(this).next();

//        //Set the name attribute of the TextBox.
//        textbox[0].name = this.id.replace("lbl", "txt");

//        //Assign the value of Label to TextBox.
//        textbox.val(label.html());

//        //When Label is clicked, hide Label and show TextBox.
//        label.click(function () {
//            $(this).hide();
//            $(this).next().show();
//        });

//        //When focus is lost from TextBox, hide TextBox and show Label.
//        textbox.focusout(function () {
//            $(this).hide();
//            $(this).prev().html($(this).val());
//            $(this).prev().show();
//        });
//    });
//});
</script>

    

FriendsFirst.Web/Views/Projections/_Contract.cshtml
@model FriendsFirst.Contracts.Contract


<div class="panel-group" id="pnlContract" role="tablist" aria-multiselectable="true">
    <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="pnlContract-heading-one">
            <h4 class="panel-title">
                <a role="button" data-toggle="collapse" data-parent="#pnlContract" href="#pnlContract-one" aria-expanded="true" aria-controls="pnlContract-one">
                    Coverages
                </a>
            </h4>
        </div>
        <div id="pnlContract-one" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="pnlContract-heading-one">
            <div class="panel-body">
                @Html.Partial("_Coverages", Model.Coverages)
            </div>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="pnlContract-heading-two">
            <h4 class="panel-title">
                <a class="collapsed" role="button" data-toggle="collapse" data-parent="#pnlContract" href="#pnlContract-two" aria-expanded="false" aria-controls="pnlContract-two">
                    Funds
                </a>
            </h4>
        </div>
        <div id="pnlContract-two" class="panel-collapse collapse" role="tabpanel" aria-labelledby="pnlContract-heading-two">
            <div class="panel-body">
                @Html.Partial("_Funds", Model.Funds)
            </div>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="pnlContract-heading-three">
            <h4 class="panel-title">
                <a class="collapsed" role="button" data-toggle="collapse" data-parent="#pnlContract" href="#pnlContract-three" aria-expanded="false" aria-controls="pnlContract-three">
                    Product
                </a>
            </h4>
        </div>
        <div id="pnlContract-three" class="panel-collapse collapse" role="tabpanel" aria-labelledby="pnlContract-heading-three">
            <div class="panel-body">
                @Html.Partial("_Product",Model.Product)
            </div>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="pnlContract-heading-four">
            <h4 class="panel-title">
                <a role="button" data-toggle="collapse" data-parent="#pnlContract" href="#pnlContract-four" aria-expanded="true" aria-controls="pnlContract-four">
                    Premium
                </a>
            </h4>
        </div>
        <div id="pnlContract-four" class="panel-collapse collapse" role="tabpanel" aria-labelledby="pnlContract-heading-four">
            <div class="panel-body">
                @Html.Partial("_Premium", Model.Premium)
            </div>
        </div>
    </div>
</div>

FriendsFirst.Web/Views/Projections/_ContractSummary.cshtml
@model FriendsFirst.Contracts.Contract 

    <div>
        <div class="row">
            <div class="col-md-6">Sum At Risk</div>
            <div class="col-md-6">@Model.SumAtRisk().ToString("C")</div>
        </div>
        <div class="row">
            <div class="col-md-6">Covered</div>
            <div class="col-md-6">
                @foreach (var covered in Model.Coverages)
                {
                    <div class="col-md-12">@covered.Name</div>
                }
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">Gross</div>
            <div class="col-md-6">@Model.Gross().ToString("C")</div>
        </div>

        <div class="row">
            <div class="col-md-6">Product</div>
            <div class="col-md-6">@Model.Product.Description</div>
        </div>

        <div class="row">
            <div class="col-md-6">Premium</div>
            <div class="col-md-6">@Model.Premium.Amount.ToString("C")</div>
        </div>
    </div>


FriendsFirst.Web/Views/Projections/_Coverages.cshtml
@model IEnumerable<FriendsFirst.Entities.Person>

<div>
    @foreach (var person in Model)
    {
    <div class="col-md-6">
        <div class="row">
            <div class="col-md-6">@Html.Label("Name") </div>
            <div class="col-md-6">@person.Name</div>
        </div>

        <div class="row">
            <div class="col-md-6">@Html.Label("DOB") </div>
            <div class="col-md-6">@person.DOB.ToShortDateString()</div>
        </div>

        <div class="row">
            <div class="col-md-6">@Html.Label("Gender") </div>
            <div class="col-md-6">@person.Gender.ToString()</div>
        </div>

        <div class="row">
            <div class="col-md-6">@Html.Label("Retirement Date")</div>
            <div class="col-md-6">@person.NormalRetirementDate.ToShortDateString()</div>
        </div>
    </div>
    }
</div>

FriendsFirst.Web/Views/Projections/_ExampleChart.cshtml
@using Chart.Mvc.ComplexChart;
@using Chart.Mvc.Extensions
@{
    var chart = new LineChart();
    chart.ComplexData.Labels.AddRange(new[] { "January", "February", "March", "April", "May", "June", "July" });
    chart.ComplexData.Datasets.AddRange(new List<ComplexDataset>
    {
        new ComplexDataset
            {
                Data = new List<double> { 65, 59, 80, 81, 56, 55, 40 },
                Label = "My First dataset",
                FillColor = "rgba(220,220,220,0.2)",
                StrokeColor = "rgba(220,220,220,1)",
                PointColor = "rgba(220,220,220,1)",
                PointStrokeColor = "#fff",
                PointHighlightFill = "#fff",
                PointHighlightStroke = "rgba(220,220,220,1)",
            },
        new ComplexDataset
            {
                Data = new List<double> { 28, 48, 40, 19, 86, 27, 90 },
                Label = "My Second dataset",
                FillColor = "rgba(151,187,205,0.2)",
                StrokeColor = "rgba(151,187,205,1)",
                PointColor = "rgba(151,187,205,1)",
                PointStrokeColor = "#fff",
                PointHighlightFill = "#fff",
                PointHighlightStroke = "rgba(151,187,205,1)",
            }
    });
}

<canvas id="myCanvas" width="600" height="400"></canvas>
@Html.CreateChart("myCanvas", chart)


FriendsFirst.Web/Views/Projections/_Funds.cshtml
@model IEnumerable<FriendsFirst.Funds.Fund>

<
@foreach (var fund in Model)
{
    <div>
        <div class="row">
            <div class="col-md-6">@Html.LabelFor(m => fund.Name) </div>
            <div class="col-md-6">@Html.DisplayFor(m => fund.Name)</div>
        </div>

        <div class="row">
            <div class="col-md-6">@Html.LabelFor(m => fund.Units.Inital) </div>
            <div class="col-md-6">@Html.DisplayFor(m => fund.Units.Inital)</div>
        </div>

        <div class="row">
            <div class="col-md-6">@Html.LabelFor(m => fund.Units.Accumulated) </div>
            <div class="col-md-6">@Html.DisplayFor(m => fund.Units.Accumulated) </div>
        </div>

        <div class="row">
            <div class="col-md-6">@Html.LabelFor(m => fund.Units.Bid) </div>
            <div class="col-md-6">@Html.DisplayFor(m => fund.Units.Bid) </div>
        </div>

        <div class="row">
            <div class="col-md-6">@Html.LabelFor(m => fund.Units.Capital) </div>
            <div class="col-md-6">@Html.DisplayFor(m => fund.Units.Capital)</div>
        </div>

        <div class="row">
            <div class="col-md-6">@Html.LabelFor(m => fund.GrowthRate) </div>
            <div class="col-md-6">@Html.DisplayFor(m => fund.GrowthRate)</div>
        </div>

        <div class="row">
            <div class="col-md-6">@Html.LabelFor(m => fund.InitalUnitDiscountFactor) </div>
            <div class="col-md-6">@Html.DisplayFor(m => fund.InitalUnitDiscountFactor)</div>
        </div>

        <div class="row">
            <div class="col-md-6">@Html.LabelFor(m => fund.InvestmentPercent) </div>
            <div class="col-md-6">@Html.DisplayFor(m => fund.InvestmentPercent)</div>
        </div>

        <div class="row">
            <div class="col-md-6">@Html.LabelFor(m => fund.ManagmentCharge) </div>
            <div class="col-md-6">@Html.EditorFor(m => fund.ManagmentCharge)</div>
        </div>
    </div>





}


FriendsFirst.Web/Views/Projections/_Premium.cshtml
@model FriendsFirst.Premiums.Premium

<div>
    <div class="row">
        <div class="col-md-6">@Html.LabelFor(m=>m.Amount)</div>
        <div class="col-md-6 editable">@Html.EditorFor(m => m.Amount)</div>
    </div>

    <div class="row">
        <div class="col-md-6">@Html.LabelFor(m => m.Frequencey)</div>
        <div class="col-md-6">@Html.EditorFor(m => m.Frequencey)</div>
    </div>

    <div class="row">
        <div class="col-md-6">@Html.LabelFor(m => m.IndexationRate)</div>
        <div class="col-md-6 editable">@Html.EditorFor(m => m.IndexationRate)</div>
    </div>

    <div class="row">
        <div class="col-md-6">@Html.LabelFor(m => m.Status)</div>
        <div class="col-md-6">@Html.EditorFor(m => m.Status)</div>
    </div>

</div>

FriendsFirst.Web/Views/Projections/_Product.cshtml
@model FriendsFirst.Products.Product

<div>
    <div class="row">
        <div class="col-md-6">@Html.LabelFor(m => m.Code) </div>
        <div class="col-md-6 ">@Html.DisplayFor(m => m.Code)</div>
    </div>

    <div class="row">
        <div class="col-md-6">@Html.LabelFor(m => m.Description) </div>
        <div class="col-md-6">@Html.DisplayFor(m => m.Description)</div>
    </div>

    <div class="row">
        <div class="col-md-6">@Html.LabelFor(p => p.AdjustedAnnuityRate)</div>
        <div class="col-md-6 editable">@Html.EditorFor(p => p.AdjustedAnnuityRate)</div>
    </div>

    <div class="row">
        <div class="col-md-6">@Html.LabelFor(p => p.ApplyPolicyChargeOnPaidUp)</div>
        <div class="col-md-6"> @Html.EditorFor(p => p.ApplyPolicyChargeOnPaidUp)</div>
    </div>

    <div class="row">
        <div class="col-md-6">@Html.LabelFor(p => p.BaseMortalityYear)</div>
        <div class="col-md-6"> @Html.EditorFor(p => p.BaseMortalityYear)</div>
    </div>

    <div class="row">
        <div class="col-md-6">@Html.LabelFor(p => p.Charge)</div>
        <div class="col-md-6"> @Html.EditorFor(p => p.Charge)</div>
    </div>

    <div class="row">
        <div class="col-md-6">@Html.LabelFor(p => p.ChargeIncreasesRate) </div>
        <div class="col-md-6">@Html.EditorFor(p => p.ChargeIncreasesRate)</div>
    </div>

    <div class="row">
        <div class="col-md-6">@Html.LabelFor(p => p.ChargePercent) </div>
        <div class="col-md-6">@Html.EditorFor(p => p.ChargePercent)</div>
    </div>

    <div class="row">
        <div class="col-md-6">@Html.LabelFor(p => p.EscalationRate) </div>
        <div class="col-md-6">@Html.EditorFor(p => p.EscalationRate)</div>
    </div>

    <div class="row">
        <div class="col-md-6">@Html.LabelFor(p => p.ExitTaxRate) </div>
        <div class="col-md-6">@Html.EditorFor(p => p.ExitTaxRate)</div>
    </div>

    <div class="row">
        <div class="col-md-6">@Html.LabelFor(p => p.Guaranteed) </div>
        <div class="col-md-6">@Html.EditorFor(p => p.Guaranteed)</div>
    </div>

    <div class="row">
        <div class="col-md-6">@Html.LabelFor(p => p.MinFundAmount) </div>
        <div class="col-md-6">@Html.EditorFor(p => p.MinFundAmount)</div>
    </div>

    <div class="row">
        <div class="col-md-6">@Html.LabelFor(p => p.MortalityImpactFactor) </div>
        <div class="col-md-6">@Html.EditorFor(p => p.MortalityImpactFactor)</div>
    </div>

    <div class="row">
        <div class="col-md-6">@Html.LabelFor(p => p.SSIS)</div>
        <div class="col-md-6"> @Html.EditorFor(p => p.SSIS)</div>
    </div>

</div>

FriendsFirst.Web/Views/Projections/_ProjectionsChart.cshtml
@model IEnumerable<FriendsFirst.Projections.ProjectedContract<FriendsFirst.Contracts.StandardSavingsContract>> 
@using Chart.Mvc.ComplexChart;
@using Chart.Mvc.Extensions;

@{
    var chart = new LineChart();

    var data = Model.Where(p => p.Date.Month == 12);
    var sumAtRiskSeries = data.Select(p => p.Contract.SumAtRisk()).ToList();
    var grossSeries = data.Select(p=>p.Contract.Gross()).ToList();
    var xSeriesLabel = data.Select(p => p.Date.ToString("yyyy")).Distinct().ToArray();

    chart.ComplexData.Labels.AddRange(xSeriesLabel);
    chart.ComplexData.Datasets.AddRange(new List<ComplexDataset>
                             {
                                new ComplexDataset
                                    {
                                        Data = grossSeries,
                                        Label = "(€) Gross",
                                        FillColor = "rgba(220,220,220,0.2)",
                                        StrokeColor = "rgba(220,220,220,1)",
                                        PointColor = "rgba(220,220,220,1)",
                                        PointStrokeColor = "#fff",
                                        PointHighlightFill = "#fff",
                                        PointHighlightStroke = "rgba(220,220,220,1)",
                                    },
                                new ComplexDataset
                                    {
                                        Data = sumAtRiskSeries,
                                        Label = "(€) Sum At Risk",
                                        FillColor = "rgba(151,187,205,0.2)",
                                        StrokeColor = "rgba(151,187,205,1)",
                                        PointColor = "rgba(151,187,205,1)",
                                        PointStrokeColor = "#fff",
                                        PointHighlightFill = "#fff",
                                        PointHighlightStroke = "rgba(151,187,205,1)",
                                    }
                            });
}

<canvas id="myCanvas" width="600" height="400"></canvas>
@Html.CreateChart("myCanvas", chart)




FriendsFirst.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Scripts/Chart.js"></script>
    @*<script src="~/MVCGridHandler.axd/script.js"></script>*@
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                <p class="nav navbar-text navbar-right">Hello, @User.Identity.Name!</p>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>